In [60]:
!pip install pandas
!pip install matplotlib

You should consider upgrading via the '/Users/pedrorodrigues/projetos_pessoais/AINets/venv/bin/python -m pip install --upgrade pip' command.
You should consider upgrading via the '/Users/pedrorodrigues/projetos_pessoais/AINets/venv/bin/python -m pip install --upgrade pip' command.


In [61]:
!pip install smop

You should consider upgrading via the '/Users/pedrorodrigues/projetos_pessoais/AINets/venv/bin/python -m pip install --upgrade pip' command.


In [95]:
import random
import pandas as pd

In [97]:
df = pd.read_csv('dataset/iris.csv', header=None)
df[4] = pd.Categorical(df[4]).codes

In [98]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df.values), columns=df.columns, index=df.index)

In [99]:
feature_max = df.max()
feature_max  = feature_max.max()
feature_min = df.min()
feature_min  = feature_min.min()

In [100]:
from numpy.random import uniform

feature_num = 4
population_size = 5
population = [uniform(low=feature_min, high=feature_max, size=feature_num) for x in range(population_size)]

In [101]:
population

[array([0.45953636, 0.54619206, 0.33736378, 0.45367873]),
 array([0.26960855, 0.31818431, 0.382586  , 0.08180056]),
 array([0.8338573 , 0.76959892, 0.05954243, 0.61980628]),
 array([0.81159817, 0.67969522, 0.14938075, 0.51740834]),
 array([0.2589658 , 0.72205243, 0.60896783, 0.60852746])]

In [ ]:
df = pd.DataFrame(scaler.inverse_transform(df),columns = df.columns)

In [122]:
train = df.loc[df[4] == 0]

In [123]:
train

0    1    2    3    4
0   5.1  3.5  1.4  0.2  0.0
1   4.9  3.0  1.4  0.2  0.0
2   4.7  3.2  1.3  0.2  0.0
3   4.6  3.1  1.5  0.2  0.0
4   5.0  3.6  1.4  0.2  0.0
5   5.4  3.9  1.7  0.4  0.0
6   4.6  3.4  1.4  0.3  0.0
7   5.0  3.4  1.5  0.2  0.0
8   4.4  2.9  1.4  0.2  0.0
9   4.9  3.1  1.5  0.1  0.0
10  5.4  3.7  1.5  0.2  0.0
11  4.8  3.4  1.6  0.2  0.0
12  4.8  3.0  1.4  0.1  0.0
13  4.3  3.0  1.1  0.1  0.0
14  5.8  4.0  1.2  0.2  0.0
15  5.7  4.4  1.5  0.4  0.0
16  5.4  3.9  1.3  0.4  0.0
17  5.1  3.5  1.4  0.3  0.0
18  5.7  3.8  1.7  0.3  0.0
19  5.1  3.8  1.5  0.3  0.0
20  5.4  3.4  1.7  0.2  0.0
21  5.1  3.7  1.5  0.4  0.0
22  4.6  3.6  1.0  0.2  0.0
23  5.1  3.3  1.7  0.5  0.0
24  4.8  3.4  1.9  0.2  0.0
25  5.0  3.0  1.6  0.2  0.0
26  5.0  3.4  1.6  0.4  0.0
27  5.2  3.5  1.5  0.2  0.0
28  5.2  3.4  1.4  0.2  0.0
29  4.7  3.2  1.6  0.2  0.0
30  4.8  3.1  1.6  0.2  0.0
31  5.4  3.4  1.5  0.4  0.0
32  5.2  4.1  1.5  0.1  0.0
33  5.5  4.2  1.4  0.2  0.0
34  4.9  3.1  1.5  0.1  0.0
35  5.0  3.2  1.2  0.2  0.0
36  5.5  3.5  1.3  0.2  0.0
37  4.9  3.1  1.5  0.1  0.0
38  4.4  3.0  1.3  0.2  0.0
39  5.1  3.4  1.5  0.2  0.0
40  5.0  3.5  1.3  0.3  0.0
41  4.5  2.3  1.3  0.3  0.0
42  4.4  3.2  1.3  0.2  0.0
43  5.0  3.5  1.6  0.6  0.0
44  5.1  3.8  1.9  0.4  0.0
45  4.8  3.0  1.4  0.3  0.0
46  5.1  3.8  1.6  0.2  0.0
47  4.6  3.2  1.4  0.2  0.0
48  5.3  3.7  1.5  0.2  0.0
49  5.0  3.3  1.4  0.2  0.0

In [118]:
df

0    1    2    3    4
0    5.1  3.5  1.4  0.2  0.0
1    4.9  3.0  1.4  0.2  0.0
2    4.7  3.2  1.3  0.2  0.0
3    4.6  3.1  1.5  0.2  0.0
4    5.0  3.6  1.4  0.2  0.0
..   ...  ...  ...  ...  ...
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

[150 rows x 5 columns]

In [116]:
# affinity
arr = df.to_numpy()
aff = 0
for i in range(len(population[0])):
    aff += (population[0][i] - arr[0][i])

In [117]:
aff

0.0